FROM humourmind/paketo-java-builder-tiny@sha256:2e4024ba26895c98ff5cb2e839d90ac7486ad1c6ba93bb82939b4ab3befa9fc1
#FROM gcr.io/paketo-buildpacks/builder:base
LABEL io.buildpacks.buildpackage.metadata="{\"id\":\"io.humourmind.paketocnb\",\"version\":\"v0.9.3\",\"stacks\":[{\"id\":\"org.cloudfoundry.stacks.cflinuxfs3\"},{\"id\":\"io.buildpacks.stacks.bionic\"}]}"
