FROM humourmind/paketo-java-builder-tiny@sha256:dca69a05438ea21e6e2262bc8f9027e33228150fed44e568b8111f07e0f6d77b
#FROM gcr.io/paketo-buildpacks/builder:base
LABEL io.buildpacks.buildpackage.metadata="{\"id\":\"io.humourmind.paketocnb\",\"version\":\"v0.7.3\",\"stacks\":[{\"id\":\"org.cloudfoundry.stacks.cflinuxfs3\"},{\"id\":\"io.buildpacks.stacks.bionic\"}]}"
