FROM humourmind/paketo-java-builder-tiny@sha256:716a653023d534410ee5fee04b1e3168f1ac251d208daa555487a4ca38b88290
#FROM gcr.io/paketo-buildpacks/builder:base
LABEL io.buildpacks.buildpackage.metadata="{\"id\":\"io.humourmind.paketocnb\",\"version\":\"v0.7.3\",\"stacks\":[{\"id\":\"org.cloudfoundry.stacks.cflinuxfs3\"},{\"id\":\"io.buildpacks.stacks.bionic\"}]}"
