description = "Ubuntu bionic base image with paketo-buildpacks for Java"

[lifecycle]
  version = "0.9.3"

[[buildpacks]]
  id = "paketo-buildpacks/java"
  uri = "docker://gcr.io/paketo-buildpacks/java:4.3.0"
#  image = "humourmind/paketo-buildpacks-java@sha256:881644d2a2495253a2e564086399a04ddb9cca8e39a5abfb14464f51f22eb359"

#[[buildpacks]]
#  id = "paketo-buildpacks/bellsoft-liberica"
#  image = "gcr.io/paketo-buildpacks/bellsoft-liberica:2.3.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/gradle"
#  image = "gcr.io/paketo-buildpacks/gradle:1.1.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/maven"
#  image = "gcr.io/paketo-buildpacks/maven:1.1.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/sbt"
#  image = "gcr.io/paketo-buildpacks/sbt:1.1.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/executable-jar"
#  image = "gcr.io/paketo-buildpacks/executable-jar:1.2.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/apache-tomcat"
#  image = "gcr.io/paketo-buildpacks/apache-tomcat:1.1.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/dist-zip"
#  image = "gcr.io/paketo-buildpacks/dist-zip:1.2.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/procfile"
#  image = "gcr.io/paketo-buildpacks/procfile:1.3.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/azure-application-insights"
#  image = "gcr.io/paketo-buildpacks/azure-application-insights:1.1.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/debug"
#  image = "gcr.io/paketo-buildpacks/debug:1.2.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/google-stackdriver"
#  image = "gcr.io/paketo-buildpacks/google-stackdriver:1.1.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/jmx"
#  image = "gcr.io/paketo-buildpacks/jmx:1.1.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/spring-boot"
#  image = "gcr.io/paketo-buildpacks/spring-boot:1.5.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/encrypt-at-rest"
#  image = "gcr.io/paketo-buildpacks/encrypt-at-rest:1.2.1"
#
#[[buildpacks]]
#  id = "paketo-buildpacks/image-labels"
#  image = "gcr.io/paketo-buildpacks/image-labels:1.0.1"

# 1 buildpack order
[[order]]
group = [

  ### Order is strictly enforced
  { id = "paketo-buildpacks/ca-certificates",            version="1.0.1", optional = true },
  { id = "paketo-buildpacks/bellsoft-liberica",          version="5.2.1" },
  { id = "paketo-buildpacks/gradle",                     version="3.3.1", optional = true },
  { id = "paketo-buildpacks/leiningen",                  version="1.2.1", optional = true },
  { id = "paketo-buildpacks/maven",                      version="3.2.1", optional = true },
  { id = "paketo-buildpacks/sbt",                        version="3.5.0", optional = true },

  ### Order determines precedence
  { id = "paketo-buildpacks/executable-jar",             version="3.1.3", optional = true },
  { id = "paketo-buildpacks/apache-tomcat",              version="3.0.0", optional = true },
  { id = "paketo-buildpacks/dist-zip",                   version="2.2.2", optional = true },
  { id = "paketo-buildpacks/spring-boot",                version="3.4.0", optional = true },
  { id = "paketo-buildpacks/procfile",                   version="3.0.0", optional = true },

  ### Order does not matter
  { id = "paketo-buildpacks/azure-application-insights", version="3.0.0", optional = true },
  { id = "paketo-buildpacks/debug",                      version="2.1.4", optional = true },
  { id = "paketo-buildpacks/google-stackdriver",         version="2.12.0", optional = true },
  { id = "paketo-buildpacks/jmx",                        version="2.1.4", optional = true },

  ### Order is strictly enforced
  { id = "paketo-buildpacks/encrypt-at-rest",            version="2.2.3", optional = true },
  { id = "paketo-buildpacks/environment-variables",      version="2.1.2", optional = true },
  { id = "paketo-buildpacks/image-labels",               version="2.0.6", optional = true }
]

# 2
[[order]]
group = [

  ### Order is strictly enforced
  { id = "paketo-buildpacks/bellsoft-liberica",          version="5.2.1" },
  { id = "paketo-buildpacks/gradle",                     version="3.3.1", optional = true },
  { id = "paketo-buildpacks/executable-jar",             version="3.1.3", optional = true },
  { id = "paketo-buildpacks/apache-tomcat",              version="3.0.0", optional = true },
  { id = "paketo-buildpacks/dist-zip",                   version="2.2.2", optional = true },
  { id = "paketo-buildpacks/spring-boot",                version="3.4.0", optional = true }
]

# 3
[[order]]
group = [

  ### Order is strictly enforced
  { id = "paketo-buildpacks/bellsoft-liberica",          version="5.2.1" },
  { id = "paketo-buildpacks/maven",                      version="3.2.1", optional = true },
  { id = "paketo-buildpacks/executable-jar",             version="3.1.3", optional = true },
  { id = "paketo-buildpacks/apache-tomcat",              version="3.0.0", optional = true },
  { id = "paketo-buildpacks/dist-zip",                   version="2.2.2", optional = true },
  { id = "paketo-buildpacks/spring-boot",                version="3.4.0", optional = true }
]

#[[labels]]

# version 1
#[stack]
#  id = "io.buildpacks.stacks.bionic"
#  build-image = "humourmind/cnb-bionic-build@sha256:8b04dcda1cd9836ee256a8ee0b0d973f6b6c6c8c9f3f7de6041dfbfea44e223d"
#  run-image = "humourmind/cnb-bionic-run@sha256:6580af825dd054dd229dee77f3cfbee9ea208000b715c5176f3977ddc9bfc04d"

# version 2
[stack]
id = "io.buildpacks.stacks.bionic"
#build-image = "humourmind/cnb-bionic-build@sha256:2cee7fc861202458c4907a28a3f767a05b943aaa406e845ccc8ca6967d87569a"
#run-image = "humourmind/cnb-bionic-run@sha256:bf1821b99703724b4316e1e46ee700d48c662e489e4523952d164a3d5031d4ab"
build-image = "humourmind/cnb-bionic-build@sha256:337b77385ecd8852b02a0537927b3539602ebb526606dac0dc52c24b411a63cb"
run-image = "humourmind/cnb-bionic-run@sha256:f712b1a9e122fb4520fd81e3814bbe026d484af8bc5854ebc52373e305400e87"
