description = "Ubuntu bionic base image with tanzu-buildpacks for Java"

[lifecycle]
  version = "0.7.3"

[[buildpacks]]
  id = "org.cloudfoundry.java"
  uri = "https://storage.googleapis.com/cnb-buildpacks/java-cnb/org.cloudfoundry.java-2.2.120.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.openjdk"
  uri = "https://storage.googleapis.com/cnb-buildpacks/openjdk-cnb/org.cloudfoundry.openjdk-1.2.14.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.buildsystem"
  uri = "https://storage.googleapis.com/cnb-buildpacks/build-system-cnb/org.cloudfoundry.buildsystem-1.2.15.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.jvmapplication"
  uri = "https://storage.googleapis.com/cnb-buildpacks/jvm-application-cnb/org.cloudfoundry.jvmapplication-1.1.12.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.tomcat"
  uri = "https://storage.googleapis.com/cnb-buildpacks/tomcat-cnb/org.cloudfoundry.tomcat-1.3.18.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.springboot"
  uri = "https://storage.googleapis.com/cnb-buildpacks/spring-boot-cnb/org.cloudfoundry.springboot-1.2.13.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.distzip"
  uri = "https://storage.googleapis.com/cnb-buildpacks/dist-zip-cnb/org.cloudfoundry.distzip-1.1.12.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.procfile"
  uri = "https://storage.googleapis.com/cnb-buildpacks/procfile-cnb/org.cloudfoundry.procfile-1.1.12.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.azureapplicationinsights"
  uri = "https://storage.googleapis.com/cnb-buildpacks/azure-application-insights-cnb/org.cloudfoundry.azureapplicationinsights-1.1.12.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.debug"
  uri = "https://storage.googleapis.com/cnb-buildpacks/debug-cnb/org.cloudfoundry.debug-1.2.11.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.googlestackdriver"
  uri = "https://storage.googleapis.com/cnb-buildpacks/google-stackdriver-cnb/org.cloudfoundry.googlestackdriver-1.1.11.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.jdbc"
  uri = "https://storage.googleapis.com/cnb-buildpacks/jdbc-cnb/org.cloudfoundry.jdbc-1.1.14.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.jmx"
  uri = "https://storage.googleapis.com/cnb-buildpacks/jmx-cnb/org.cloudfoundry.jmx-1.1.12.tgz"

[[buildpacks]]
  id = "org.cloudfoundry.springautoreconfiguration"
  uri = "https://storage.googleapis.com/cnb-buildpacks/spring-auto-reconfiguration-cnb/org.cloudfoundry.springautoreconfiguration-1.1.11.tgz"

# buildpack order
[[order]]
group = [
  { id = "org.cloudfoundry.openjdk",                    version = "1.2.14"},
  { id = "org.cloudfoundry.buildsystem",                version = "1.2.15",   optional = true},
  { id = "org.cloudfoundry.jvmapplication",             version = "1.1.12"},
  { id = "org.cloudfoundry.tomcat",                     version = "1.3.18"},
  { id = "org.cloudfoundry.springboot",                 version = "1.2.13"},
  { id = "org.cloudfoundry.distzip",                    version = "1.1.12"},
  { id = "org.cloudfoundry.procfile",                   version = "1.1.12",   optional = true},
  { id = "org.cloudfoundry.debug",                      version = "1.2.11",   optional = true},
  { id = "org.cloudfoundry.jdbc",                       version = "1.1.14",   optional = true },
  { id = "org.cloudfoundry.jmx",                        version = "1.1.12",   optional = true },
  { id = "org.cloudfoundry.springautoreconfiguration",  version = "1.1.11",   optional = true }
]

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "humourmind/cnb-build:tiny"
  run-image = "humourmind/cnb-run:tiny"
