FROM humourmind/tanzu-java-builder-tiny:0.7.3
LABEL io.buildpacks.buildpackage.metadata="{\"id\":\"io.humourmind.tanzucnb\",\"version\":\"v0.7.3\",\"stacks\":[{\"id\":\"org.cloudfoundry.stacks.cflinuxfs3\"},{\"id\":\"io.buildpacks.stacks.bionic\"}]}"
