apiVersion: kpack.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: paketocnb-java-builder-tiny
spec:
  tag: harbor.sys.humourmind.com/tbs/build-service/paketo-bs-java-builder-tiny:0.9.3
  serviceAccountRef:
    name: default
    namespace: kna
  stack:
    name: paketocnb-java-stack-tiny
    kind: ClusterStack
  store:
    name: paketocnb-java-store-tiny
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/bellsoft-liberica
    - id: paketo-buildpacks/gradle
    - id: paketo-buildpacks/executable-jar
    - id: paketo-buildpacks/apache-tomcat
    - id: paketo-buildpacks/dist-zip
    - id: paketo-buildpacks/spring-boot
  - group:
    - id: paketo-buildpacks/bellsoft-liberica
    - id: paketo-buildpacks/maven
    - id: paketo-buildpacks/executable-jar
    - id: paketo-buildpacks/apache-tomcat
    - id: paketo-buildpacks/dist-zip
    - id: paketo-buildpacks/spring-boot
